Header always set X-Powered-By "EASM Lab"
DirectoryIndex index.html

<VirtualHost *:80>
    ServerName easm-web
    DocumentRoot "/usr/local/apache2/htdocs"
    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>
